### ISSUE TITLE
Implement E2E tests: `TopicInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#102]
```[tasklist]
### Tasks
 - [ ] Implement `TopicInfoQuery` E2E tests: Java
 - [ ] Implement `TopicInfoQuery` E2E tests: Javascript
 - [ ] Implement `TopicInfoQuery` E2E tests: Go
 - [ ] Implement `TopicInfoQuery` E2E tests: C++
 - [ ] Implement `TopicInfoQuery` E2E tests: Rust
 - [ ] Implement `TopicInfoQuery` E2E tests: Swift
 - [ ] Implement `TopicInfoQuery` E2E tests: TCK
```
