### ISSUE TITLE
Implement E2E tests: `TopicMessageSubmitTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#105]
```[tasklist]
### Tasks
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: Java
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: Javascript
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: Go
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: C++
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: Rust
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: Swift
 - [ ] Implement `TopicMessageSubmitTransaction` E2E tests: TCK
```
