### ISSUE TITLE
Implement E2E tests: `EthereumTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#108]
```[tasklist]
### Tasks
 - [ ] Implement `EthereumTransaction` E2E tests: Java
 - [ ] Implement `EthereumTransaction` E2E tests: Javascript
 - [ ] Implement `EthereumTransaction` E2E tests: Go
 - [ ] Implement `EthereumTransaction` E2E tests: C++
 - [ ] Implement `EthereumTransaction` E2E tests: Rust
 - [ ] Implement `EthereumTransaction` E2E tests: Swift
 - [ ] Implement `EthereumTransaction` E2E tests: TCK
```
