### ISSUE TITLE
Implement E2E tests: `TokenFeeScheduleUpdateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#147]
```[tasklist]
### Tasks
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: Java
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: Javascript
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: Go
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: C++
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: Rust
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: Swift
 - [ ] Implement `TokenFeeScheduleUpdateTransaction` E2E tests: TCK
```
