### ISSUE TITLE
Implement E2E tests: `TokenFreezeTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#150]
```[tasklist]
### Tasks
 - [ ] Implement `TokenFreezeTransaction` E2E tests: Java
 - [ ] Implement `TokenFreezeTransaction` E2E tests: Javascript
 - [ ] Implement `TokenFreezeTransaction` E2E tests: Go
 - [ ] Implement `TokenFreezeTransaction` E2E tests: C++
 - [ ] Implement `TokenFreezeTransaction` E2E tests: Rust
 - [ ] Implement `TokenFreezeTransaction` E2E tests: Swift
 - [ ] Implement `TokenFreezeTransaction` E2E tests: TCK
```
