### ISSUE TITLE
Implement E2E tests: `TokenInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#156]
```[tasklist]
### Tasks
 - [ ] Implement `TokenInfoQuery` E2E tests: Java
 - [ ] Implement `TokenInfoQuery` E2E tests: Javascript
 - [ ] Implement `TokenInfoQuery` E2E tests: Go
 - [ ] Implement `TokenInfoQuery` E2E tests: C++
 - [ ] Implement `TokenInfoQuery` E2E tests: Rust
 - [ ] Implement `TokenInfoQuery` E2E tests: Swift
 - [ ] Implement `TokenInfoQuery` E2E tests: TCK
```
