### ISSUE TITLE
Implement E2E tests: `TokenNftInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#162]
```[tasklist]
### Tasks
 - [ ] Implement `TokenNftInfoQuery` E2E tests: Java
 - [ ] Implement `TokenNftInfoQuery` E2E tests: Javascript
 - [ ] Implement `TokenNftInfoQuery` E2E tests: Go
 - [ ] Implement `TokenNftInfoQuery` E2E tests: C++
 - [ ] Implement `TokenNftInfoQuery` E2E tests: Rust
 - [ ] Implement `TokenNftInfoQuery` E2E tests: Swift
 - [ ] Implement `TokenNftInfoQuery` E2E tests: TCK
```
