### ISSUE TITLE
Implement E2E tests: `TokenPauseTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#165]
```[tasklist]
### Tasks
 - [ ] Implement `TokenPauseTransaction` E2E tests: Java
 - [ ] Implement `TokenPauseTransaction` E2E tests: Javascript
 - [ ] Implement `TokenPauseTransaction` E2E tests: Go
 - [ ] Implement `TokenPauseTransaction` E2E tests: C++
 - [ ] Implement `TokenPauseTransaction` E2E tests: Rust
 - [ ] Implement `TokenPauseTransaction` E2E tests: Swift
 - [ ] Implement `TokenPauseTransaction` E2E tests: TCK
```
