### ISSUE TITLE
Implement E2E tests: `TokenUpdateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#177]
```[tasklist]
### Tasks
 - [ ] Implement `TokenUpdateTransaction` E2E tests: Java
 - [ ] Implement `TokenUpdateTransaction` E2E tests: Javascript
 - [ ] Implement `TokenUpdateTransaction` E2E tests: Go
 - [ ] Implement `TokenUpdateTransaction` E2E tests: C++
 - [ ] Implement `TokenUpdateTransaction` E2E tests: Rust
 - [ ] Implement `TokenUpdateTransaction` E2E tests: Swift
 - [ ] Implement `TokenUpdateTransaction` E2E tests: TCK
```
