### ISSUE TITLE
Implement E2E tests: `TokenWipeTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#180]
```[tasklist]
### Tasks
 - [ ] Implement `TokenWipeTransaction` E2E tests: Java
 - [ ] Implement `TokenWipeTransaction` E2E tests: Javascript
 - [ ] Implement `TokenWipeTransaction` E2E tests: Go
 - [ ] Implement `TokenWipeTransaction` E2E tests: C++
 - [ ] Implement `TokenWipeTransaction` E2E tests: Rust
 - [ ] Implement `TokenWipeTransaction` E2E tests: Swift
 - [ ] Implement `TokenWipeTransaction` E2E tests: TCK
```
