### ISSUE TITLE
Implement E2E tests: `TransactionReceiptQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#183]
```[tasklist]
### Tasks
 - [ ] Implement `TransactionReceiptQuery` E2E tests: Java
 - [ ] Implement `TransactionReceiptQuery` E2E tests: Javascript
 - [ ] Implement `TransactionReceiptQuery` E2E tests: Go
 - [ ] Implement `TransactionReceiptQuery` E2E tests: C++
 - [ ] Implement `TransactionReceiptQuery` E2E tests: Rust
 - [ ] Implement `TransactionReceiptQuery` E2E tests: Swift
 - [ ] Implement `TransactionReceiptQuery` E2E tests: TCK
```
