### ISSUE TITLE
Implement E2E tests: `TransactionRecordQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#186]
```[tasklist]
### Tasks
 - [ ] Implement `TransactionRecordQuery` E2E tests: Java
 - [ ] Implement `TransactionRecordQuery` E2E tests: Javascript
 - [ ] Implement `TransactionRecordQuery` E2E tests: Go
 - [ ] Implement `TransactionRecordQuery` E2E tests: C++
 - [ ] Implement `TransactionRecordQuery` E2E tests: Rust
 - [ ] Implement `TransactionRecordQuery` E2E tests: Swift
 - [ ] Implement `TransactionRecordQuery` E2E tests: TCK
```
