### ISSUE TITLE
Document E2E tests: `AccountCreateTransaction`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-tck#20]
Document the end to end test plan to create an account. 
https://github.com/hashgraph/hedera-sdk-tck/blob/main/test-specifications/createAccount.md
```[tasklist]
### Tasks
- [x] Create createAccount.md in the test specifications folder
- [x] Document the test cases
- [ ] https://github.com/hashgraph/hedera-sdk-tck/issues/199
- [ ] https://github.com/hashgraph/hedera-sdk-tck/issues/208
- [ ] https://github.com/hashgraph/hedera-sdk-tck/issues/210
```

**Comment by rwalworth** [comment]
Reopening since we're implementing more new standards and conventions for our test documentation. This should be closed when #200 is merged.
