### ISSUE TITLE
Document E2E tests: `AccountUpdateTransaction`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-tck#21]
Document the end to end test plan to update an account.

```[tasklist]
### Tasks
- [x] Create an updateAccount.md file under the test specifications folder
- [x] Document the end to end tests
- [ ] https://github.com/hashgraph/hedera-sdk-tck/issues/207
```

**Comment by rwalworth** [comment]
The documentation should be updated to match the guidelines and conventions we've established (can look at `accountCreateTransaction.md` as an example).
