### ISSUE TITLE
Implement E2E tests: `AccountInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#51]
```[tasklist]
### Tasks
 - [ ] Implement `AccountInfoQuery` E2E tests: Java
 - [ ] Implement `AccountInfoQuery` E2E tests: Javascript
 - [ ] Implement `AccountInfoQuery` E2E tests: Go
 - [ ] Implement `AccountInfoQuery` E2E tests: C++
 - [ ] Implement `AccountInfoQuery` E2E tests: Rust
 - [ ] Implement `AccountInfoQuery` E2E tests: Swift
 - [ ] Implement `AccountInfoQuery` E2E tests: TCK
```
