### ISSUE TITLE
Implement E2E tests: `TransferTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#54]
```[tasklist]
### Tasks
 - [ ] Implement `TransferTransaction` E2E tests: Java
 - [ ] Implement `TransferTransaction` E2E tests: Javascript
 - [ ] Implement `TransferTransaction` E2E tests: Go
 - [ ] Implement `TransferTransaction` E2E tests: C++
 - [ ] Implement `TransferTransaction` E2E tests: Rust
 - [ ] Implement `TransferTransaction` E2E tests: Swift
 - [ ] Implement `TransferTransaction` E2E tests: TCK
```
