### ISSUE TITLE
Implement E2E tests: `FileCreateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#57]
```[tasklist]
### Tasks
 - [ ] Implement `FileCreateTransaction` E2E tests: Java
 - [ ] Implement `FileCreateTransaction` E2E tests: Javascript
 - [ ] Implement `FileCreateTransaction` E2E tests: Go
 - [ ] Implement `FileCreateTransaction` E2E tests: C++
 - [ ] Implement `FileCreateTransaction` E2E tests: Rust
 - [ ] Implement `FileCreateTransaction` E2E tests: Swift
 - [ ] Implement `FileCreateTransaction` E2E tests: TCK
```
