### ISSUE TITLE
Implement E2E tests: `FileAppendTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#60]
```[tasklist]
### Tasks
 - [ ] Implement `FileAppendTransaction` E2E tests: Java
 - [ ] Implement `FileAppendTransaction` E2E tests: Javascript
 - [ ] Implement `FileAppendTransaction` E2E tests: Go
 - [ ] Implement `FileAppendTransaction` E2E tests: C++
 - [ ] Implement `FileAppendTransaction` E2E tests: Rust
 - [ ] Implement `FileAppendTransaction` E2E tests: Swift
 - [ ] Implement `FileAppendTransaction` E2E tests: TCK
```
