### ISSUE TITLE
Implement E2E tests: `FileUpdateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#63]
```[tasklist]
### Tasks
 - [ ] Implement `FileUpdateTransaction` E2E tests: Java
 - [ ] Implement `FileUpdateTransaction` E2E tests: Javascript
 - [ ] Implement `FileUpdateTransaction` E2E tests: Go
 - [ ] Implement `FileUpdateTransaction` E2E tests: C++
 - [ ] Implement `FileUpdateTransaction` E2E tests: Rust
 - [ ] Implement `FileUpdateTransaction` E2E tests: Swift
 - [ ] Implement `FileUpdateTransaction` E2E tests: TCK
```
