### ISSUE TITLE
Implement E2E tests: `FileDeleteTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#66]
```[tasklist]
### Tasks
 - [ ] Implement `FileDeleteTransaction` E2E tests: Java
 - [ ] Implement `FileDeleteTransaction` E2E tests: Javascript
 - [ ] Implement `FileDeleteTransaction` E2E tests: Go
 - [ ] Implement `FileDeleteTransaction` E2E tests: C++
 - [ ] Implement `FileDeleteTransaction` E2E tests: Rust
 - [ ] Implement `FileDeleteTransaction` E2E tests: Swift
 - [ ] Implement `FileDeleteTransaction` E2E tests: TCK
```
