### ISSUE TITLE
Implement E2E tests: `FileInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#69]
```[tasklist]
### Tasks
 - [ ] Implement `FileInfoQuery` E2E tests: Java
 - [ ] Implement `FileInfoQuery` E2E tests: Javascript
 - [ ] Implement `FileInfoQuery` E2E tests: Go
 - [ ] Implement `FileInfoQuery` E2E tests: C++
 - [ ] Implement `FileInfoQuery` E2E tests: Rust
 - [ ] Implement `FileInfoQuery` E2E tests: Swift
 - [ ] Implement `FileInfoQuery` E2E tests: TCK
```
