### ISSUE TITLE
Implement E2E tests: `ContractCallQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#75]
```[tasklist]
### Tasks
 - [ ] Implement `ContractCallQuery` E2E tests: Java
 - [ ] Implement `ContractCallQuery` E2E tests: Javascript
 - [ ] Implement `ContractCallQuery` E2E tests: Go
 - [ ] Implement `ContractCallQuery` E2E tests: C++
 - [ ] Implement `ContractCallQuery` E2E tests: Rust
 - [ ] Implement `ContractCallQuery` E2E tests: Swift
 - [ ] Implement `ContractCallQuery` E2E tests: TCK
```
