### ISSUE TITLE
Implement E2E tests: `ContractUpdateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#81]
```[tasklist]
### Tasks
 - [ ] Implement `ContractUpdateTransaction` E2E tests: Java
 - [ ] Implement `ContractUpdateTransaction` E2E tests: Javascript
 - [ ] Implement `ContractUpdateTransaction` E2E tests: Go
 - [ ] Implement `ContractUpdateTransaction` E2E tests: C++
 - [ ] Implement `ContractUpdateTransaction` E2E tests: Rust
 - [ ] Implement `ContractUpdateTransaction` E2E tests: Swift
 - [ ] Implement `ContractUpdateTransaction` E2E tests: TCK
```
