### ISSUE TITLE
Implement E2E tests: `ContractInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#87]
```[tasklist]
### Tasks
 - [ ] Implement `ContractInfoQuery` E2E tests: Java
 - [ ] Implement `ContractInfoQuery` E2E tests: Javascript
 - [ ] Implement `ContractInfoQuery` E2E tests: Go
 - [ ] Implement `ContractInfoQuery` E2E tests: C++
 - [ ] Implement `ContractInfoQuery` E2E tests: Rust
 - [ ] Implement `ContractInfoQuery` E2E tests: Swift
 - [ ] Implement `ContractInfoQuery` E2E tests: TCK
```
