### ISSUE TITLE
Implement E2E tests: `ContractBytecodeQuery`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#90]
```[tasklist]
### Tasks
 - [ ] Implement `ContractBytecodeQuery` E2E tests: Java
 - [ ] Implement `ContractBytecodeQuery` E2E tests: Javascript
 - [ ] Implement `ContractBytecodeQuery` E2E tests: Go
 - [ ] Implement `ContractBytecodeQuery` E2E tests: C++
 - [ ] Implement `ContractBytecodeQuery` E2E tests: Rust
 - [ ] Implement `ContractBytecodeQuery` E2E tests: Swift
 - [ ] Implement `ContractBytecodeQuery` E2E tests: TCK
```
