### ISSUE TITLE
Implement E2E tests: `TopicCreateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-tck#93]
```[tasklist]
### Tasks
 - [ ] Implement `TopicCreateTransaction` E2E tests: Java
 - [ ] Implement `TopicCreateTransaction` E2E tests: Javascript
 - [ ] Implement `TopicCreateTransaction` E2E tests: Go
 - [ ] Implement `TopicCreateTransaction` E2E tests: C++
 - [ ] Implement `TopicCreateTransaction` E2E tests: Rust
 - [ ] Implement `TopicCreateTransaction` E2E tests: Swift
 - [ ] Implement `TopicCreateTransaction` E2E tests: TCK
```
